#+TITLE: Curriculum Vitae
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: Abril, 2015
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LANGUAGE:  es
#+LaTeX_CLASS: memoir-article
#+LATEX_HEADER: \usepackage{mathpazo}
#+LATEX_HEADER: \usepackage{memhfixc}
#+LATEX_HEADER: \usepackage{mempatch}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LATEX_HEADER: \geometry{verbose,tmargin=2cm,bmargin=2cm,lmargin=2cm,rmargin=2cm}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{itemsep=-2pt}
#+LATEX_HEADER: \hypersetup{bookmarks=true, breaklinks=true,pdftitle={Curriculum}, pdfauthor={Oscar Perpiñán Lamigueiro}, pdfnewwindow=true, colorlinks=true,linkcolor=Brown,citecolor=BrickRed, filecolor=black,urlcolor=Blue}           
#+LATEX_HEADER: \counterwithout{section}{chapter}
#+LATEX_HEADER: \setsecheadstyle{\Large\scshape\bfseries\raggedright}
#+LATEX_HEADER: \setsubsubsecheadstyle{\itshape\raggedright}

* Datos Personales

** Generales

- Nombre: Oscar Perpiñán Lamigueiro
- Correo electrónico: [[mailto:oscar.perpinan@upm.es][oscar.perpinan@upm.es]]
- Web: [[http://oscarperpinan.github.io]]
- LinkedIn: [[http://es.linkedin.com/in/oscarperpinan]]

** Contrato vigente en ámbito universitario

- Universidad Politécnica de Madrid
  - Escuela Técnica Superior de Ingeniería de Diseño Industrial
  - Departamento de Ingeniería Eléctrica, Eléctrónica, Automática, y de Física Aplicada
  - Categoría Actual: Profesor Ayudante Doctor


* Títulos Académicos

** Doctor
  - ETSII-UNED (Abr-2008)
  - Programa de Doctorado "Sistemas de Ingeniería Eléctrica, Electrónica y de Control"
  - Tesis ``Grandes Centrales Fotovoltaicas: producción, seguimiento y ciclo de vida'' calificada con Sobresaliente cum laude y Premio Extraordinario.

** Ingeniero de Telecomunicación
  - ETSIT-UPM (Dic-1999)
  - Especialidad en Radiocomunicación
  - Proyecto de Fin de Carrera: ``Desarrollo de un protocolo de medida de lámparas fluorescentes para instalaciones fotovoltaicas de electrificación rural''


* Puestos Docentes Desempeñados

** Profesor Asociado
- Centro: Escuela Universitaria de Ingenieros Técnicos Industriales, Universidad Politécnica de Madrid.
- Régimen de Dedicación: Parcial (6+6).
- Actividad: Docencia
- Fecha Nombramiento: 14 de Noviembre de 2008
- Fecha Cese: 30 de Septiembre de 2010

** Profesor Ayudante Doctor
- Centro: Escuela Técnica Superior de Ingeniería de Diseño Industrial, Universidad Politécnica de Madrid.
- Régimen de Dedicación: Completa.
- Actividad: Docencia e Investigación
- Fecha Nombramiento: 4 de Octubre de 2010.
- Fecha Cese: Vigente en la actualidad.

\newpage
* Actividad Docente

** Escuela Técnica Superior de Ingeniería de Diseño Industrial
#+ATTR_LaTeX: :align p{18mm}p{10mm}p{40mm}p{40mm}p{10mm}p{15mm}p{10mm}
| Curso\\académico | Cuat. | Asignatura         | Titulación         | Curso Titulación | Carácter          | Horas |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|                  | <3> | <18>               | <18>               | <3> |                   |   <5> |
|        2008-2009 |   1 | Fund. de Electrotecnia | Ing. Técnico Industrial (Esp. Eléctricos) |   1 | Teoría            |    75 |
|        2008-2009 |   2 | Fund. de Electrotecnia | Ing. Técnico Industrial (Esp. Mecánicos) |   1 | Teoría y Práctica |    75 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2009-2010 |   1 | Fund. de Electrotecnia | Ing. Técnico Industrial (Esp. Eléctricos) |   1 | Teoría            |    75 |
|        2009-2010 |   2 | Fund. de Electrotecnia | Ing. Técnico Industrial (Esp. Mecánicos) |   1 | Teoría y Práctica |    75 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2010-2011 |   1 | Teoría de Circuitos II | Ing. Técnico Industrial (Esp. Eléctricos) |   2 | Práctica          |    75 |
|        2010-2011 |   2 | Electrometría      | Ing. Técnico Industrial (Esp. Eléctricos) |   1 | Práctica          |    30 |
|        2010-2011 |   2 | Teoría de Circuitos I | Grado en Ing. Eléctrica |   1 | Práctica          |    45 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2011-2012 |   1 | Teoría de Circuitos | Grado en Ing. Química |   2 | Práctica          |    15 |
|        2011-2012 |   1 | Teoría de Circuitos | Grado en Ing. Electrónica Industrial y Automática |   2 | Teoría            |    45 |
|        2011-2012 |   1 | Teoría de Circuitos | Grado en Ing. Electrónica Industrial y Automática |   2 | Práctica          |    15 |
|        2011-2012 |   1 | Teoría de Circuitos | Grado en Ing. Eléctrica |   2 | Práctica          |    15 |
|        2011-2012 |   2 | Teoría de Circuitos | Grado en Ing. en Diseño Industrial |   2 | Teoría y Práctica |    60 |
|        2011-2012 |   2 | Teoría de Circuitos | Grado en Ing. Mecánica |   2 | Práctica          |    15 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2012-2013 |   1 | Teoría de Circuitos III | Grado en Ing. Eléctrica |   3 | Práctica          |    15 |
|        2012-2013 |   1 | Teoría de Circuitos | Grado en Ing. Química |   2 | Teoría            |    41 |
|        2012-2013 |   1 | Teoría de Circuitos | Grado en Ing. Electrónica Industrial y Automática |   2 | Práctica          |    15 |
|        2012-2013 |   2 | Diseño Avanzado de Sistemas de Energía Solar | Master Universitario en Ingeniería de la Energía |   1 | Teoría y Práctica |  10.5 |
|        2012-2013 |   2 | Teoría de Circuitos | Grado en Ing. en Diseño Industrial |   2 | Teoría            |    41 |
|        2012-2013 |   2 | Teoría de Circuitos | Grado en Ing. Mecánica |   2 | Práctica          |    30 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2013-2014 |   1 | Teoría de Circuitos III | Grado en Ing. Eléctrica |   3 | Práctica          |    64 |
|        2013-2014 |   1 | Teoría de Circuitos | Grado en Ing. Electrónica Industrial y Automática |   2 | Teoría y Práctica |    83 |
|        2013-2014 |   2 | Diseño Avanzado de Sistemas de Energía Solar | Master Universitario en Ingeniería de la Energía |   1 | Teoría y Práctica |  10.5 |
|        2013-2014 |   2 | Teoría de Circuitos | Grado en Ing. Mecánica |   2 | Teoría y Práctica |    67 |
|        2013-2014 |   2 | Teoría de Circuitos | Grado en Ing. de Diseño Industrial |   2 | Teoría y Práctica |    48 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|        2014-2015 |   1 | Teoría de Circuitos III | Grado en Ing. Eléctrica |   3 | Práctica          |    64 |
|        2014-2015 |   1 | Teoría de Circuitos | Grado en Ing. Electrónica Industrial y Automática |   2 | Teoría y Práctica |    83 |
|        2014-2015 |   2 | Diseño Avanzado de Sistemas de Energía Solar | Master Universitario en Ingeniería de la Energía |   1 | Teoría y Práctica |  10.5 |
|        2014-2015 |   2 | Teoría de Circuitos | Grado en Ing. Mecánica |   2 | Teoría y Práctica |    67 |
|        2014-2015 |   2 | Teoría de Circuitos | Grado en Ing. de Diseño Industrial |   2 | Teoría y Práctica |    48 |
|------------------+-----+--------------------+--------------------+-----+-------------------+-------|
|                  |     |                    |                    |     | Total             |  1281 |




  
** Escuela de Organización Industrial

Colaborador en el Máster de Energías Renovables y Mercado Energético (MERME) de la Escuela de Organización Industrial:

- Cursos 2014-2015, 2013-2014, 2012-2013, 2011-2012, 2010-2011, y 2009-2010: Asignatura troncal ``Energía Solar Fotovoltaica'' con un total de 70 horas lectivas.

- Curso 2008-2009: Asignatura troncal ``Energía Solar Fotovoltaica'' con un total de 40 horas lectivas y asignatura optativa ``Energía Solar Fotovoltaica Avanzada'' con un total de 40 horas lectivas. 

- Sesiones individuales con un total de 58 horas lectivas desde el curso 2001/2002 hasta el 2007/2008.
  

* Actividad Investigadora

** Miembro del Grupo de Investigación ``Sistemas Fotovoltaicos''

Reconocido como consolidado por la Universidad Politécnica de Madrid, con tres líneas de investigación: Sistemas fotovoltaicos conectados a la red, Sistemas fotovoltaicos autónomos e híbridos y Electrificación rural fotovoltaica.

** Dirección de Tesis Doctorales 

- Codirección de la Tesis Doctoral "Inserçao en Grande Escala de Geraçao Solar Fotovoltaica em Sistemas Elétricos de Potência" de Marcelo Pinho Almeida, junto con el profesor Roberto Zilles, del Instituto de Energia e Ambiente de la Universidad de Sao Paulo.

- Codirección de la Tesis Doctoral "New methodologies and improved models in the estimation of solar irradiation" de Fernando Antoñanzas, junto con el profesor Francisco Javier Martínez de Ascacíbar, del grupo EDMANS de la Universidad de la Rioja.

- Codirección de la Tesis Doctoral "Penetración de la Energía Fotovoltaica en el Sistema Eléctrico peninsular español. Condiciones del Mercado Eléctrico y Red de Transporte" de José Melguizo, junto con el profesor Manuel Castro Gil, catedrático del DIEEC-ETSII (UNED).
  

** Dirección de Trabajos Tutelados
*** ETSIDI
- “Estimation de la puissance des systèmes photovoltaïques avec Machine Learning”, Imrane Dhmani (Université Montpellier 2). 2013/2014, 15 ECTS.
- “Une estimation de puissance dans un système photovoltaique avec Random Forest”, Kobaa Abdeslam (Université Montpellier 2). 2013/2014, 15 ECTS.
*** Escuela de Organización Industrial
    - 2013-2014:
      - ``Electrificación Rural mediante Sistema Híbrido Eólico-Fotovoltáico en Roraima, Brasil''
      - ``Electrificación Rural Aislada Fotovoltaica (ERAF) a Institutos de Telesecundaria en San Pedro Carchá, Alta Verapaz, Guatemala.''
    - 2011-2012:
      - ``Servicios energéticos Renovables: E. Fotovoltaica, E. Mini-eólica y eficiencia energética en entornos urbanos''
    - 2010-2011:
      - ``Comparativa y análisis de variabilidad espacio-temporal entre las medidas de radiación solar terrestres (SIAR) y satelitales (CM SAF). Estudio de productividad potencial''.
    - 2008/2009:
      - "La integración de la generación distribuida de origen fotovoltaico con la red de distribución actual.
    - 2007/2008:
      - "Proyecto de Instalación Fotovoltaica de 100 kW para la conexión a red de BT. Sistemas Híbridos Fotovoltaico-Diesel"
    - 2006/2007:
      - "Instalación solar Polígono Albresa"
      - "Parque solar FV en Huelva"
      - "Instalación solar en Jarandilla de la Vera"
    - 2005/2006:
      - "Planta seguimiento BT: estudio de posibilidades en mercado libre"
    - 2004/2005
      - "Sistema fotovoltaico conectado a red, Fontiveros (Ávila)"
      - "Instalación fotovoltaica conectada a red"
    - 2003/2004:
      - "Integración de un sistema de energía solar en un centro escolar"
    - 2002/2003:
      - "Sistema fotovoltaico conectado a red integrado en pérgolas del Ayuntamiento de Tres Cantos"
    - 2001/2002:
      - "PVSOUNDLESS: Sistema fotovoltaico integrado en una barrera acústica"

*** EUREC
Supervisión on-site de Proyectos de Fin de Máster del European Máster in Renewable Energy de la Agencia EUREC en los cursos 2004/2005 y 2003/2004.

* Libros y Capítulos en Libros

** Displaying time series, spatial and space-time data with R
O. Perpiñán, Chapman and Hall/CRC, 2014, ISBN 9781466565203. http://oscarperpinan.github.com/spacetime-vis/

** Energía Solar Fotovoltaica
O. Perpiñán, 2014. Libro autoeditado, publicado online con licencia Creative Commons.  [[http://oscarperpinan.github.com/esf]]

** Diseño de Sistemas Fotovoltaicos
*O. Perpiñán*, M.A. Castro Gil, A. Colmenar, Promotora General de Estudios, S.A., 2012, ISBN: 978-84-95693-72-3
  
** Soft Computing Applications for Renewable Energy and Energy Efficiency
F. Antonanzas-Torres, A. Sanz-Garcia, J. Antonanzas, *O. Perpiñán*, F.J. Martínez-de-Pisón, Current Status and Future Trends of the Evaluation of Solar Global Irradiation using Soft-Computing-Based Models, en Soft Computing Applications for Renewable Energy and Energy Efficiency. M. Cascales, M. Sánchez-Lozano, A.D. Masegosa, C. Cruz,  Series in Advances in Environmental Engineering and Green Technologies, IGI Global, 2015, (1-22) ISBN 9781466666320. [[http://dx.doi.org/10.4018/978-1-4666-6631-3.ch001][10.4018/978-1-4666-6631-3.ch001]].

** Sistemas de bombeo eólicos y fotovoltaicos
M. Castro,A. Colmenar, R.P. Fiffe, M. Pérez, *O. Perpiñán*, J.M. Perulero. Monografías de Energías Renovables, Promotora General de Estudios, S.A., 2011, ISBN 84-95693-67-9
  
** Energía eólica
M. Castro, A. Colmenar, *O. Perpiñán*, C. Sánchez Naranjo. Monografías de Energías Renovables, Promotora General de Estudios, S.A., 2011, ISBN 84-86505-69-3.
  
* Artículos en Revistas 
** Publicaciones Internacionales
Disponibles en [[http://oscarperpinan.github.io/#papers]]

- M. Pinho Almeida, *O. Perpiñán*, L. Narvarte, PV Power Forecast Using a Nonparametric PV Model. Solar Energy 115 (May): 354–68. doi:10.1016/j.solener.2015.03.006.\\ (Índice de impacto: 3.868, Tercil T1 en categoría /Energy & Fuels/)

- F. Antonanzas-Torres, F.J. Martínez de Pisón, J. Antonanzas, *O. Perpiñán*, Downscaling of global solar irradiation in complex areas in R, Journal of Renewable and Sustainable Energy, 6, 063105 (2014), [[http://dx.doi.org/10.1063/1.4901539][10.1063/1.4901539]] \\ (Índice de impacto: 0.925, Tercil T3 en categoría /Energy & Fuels/)

- F. Antonanzas-Torres, A. Sanz-Garcia, F. J. Martínez-de-Pisón, *O. Perpiñán*, J. Polo, Towards downscaling of aerosol gridded dataset for improving solar resource assessment. Application to Spain, Renewable Energy, Volume 71, November 2014, Pages 534-544, [[http://dx.doi.org/10.1016/j.renene.2014.06.010][10.1016/j.renene.2014.06.010]]. \\ (Índice de impacto: 3.85, Tercil T1 en categoría /Energy & Fuels/)

- F. Antonanzas-Torres, A. Sanz-Garcia, F.J. Martínez-de-Pisón, *O. Perpiñán*, Evaluation and improvement of empirical models of global solar irradiation: Case study northern Spain, Renewable Energy, Volume 60, December 2013, Pages 604-614, ISSN 0960-1481, [[http://dx.doi.org/10.1016/j.renene.2013.06.008][10.1016/j.renene.2013.06.008]]. \\ (Índice de impacto: 2.99, Tercil T1 en categoría /Energy & Fuels/)

- F. Antoñanzas, F. Cañizares, *O. Perpiñán*, Comparative assessment of global irradiation from a satellite estimate model (CM SAF) and on-ground measurements (SIAR): a Spanish case study, Renewable and Sustainable Energy Reviews, Volume 21, May 2013, Pages 248-261, [[http://dx.doi.org/10.1016/j.rser.2012.12.033][10.1016/j.rser.2012.12.033]]. \\ (Índice de impacto: 5.63, Tercil T1 en categoría /Energy & Fuels/)

- *O. Perpiñán*, J. Marcos, E. Lorenzo, Electrical Power Fluctuations in a Network of DC/AC inverters in a Large PV Plant: relationship between correlation, distance and time scale, Solar Energy, Volume 88, February 2013, [[http://dx.doi.org/10.1016/j.solener.2012.12.004][10.1016/j.solener.2012.004]]. \\ (Índice de impacto: 2.95, Tercil T1 en categoría /Energy & Fuels/)

- *O. Perpiñán*, M.A. Sánchez-Urán, F. Álvarez, J. Ortego, F. Garnacho, Signal analysis and feature generation for pattern identification of partial discharges in high-voltage equipment, Electric Power Systems Research, 2013, 95:C (56-65), [[http://dx.doi.org/10.1016/j.epsr.2012.08.016][10.1016/j.epsr.2012.08.016]].\\ (Índice de impacto: 1.69, Tercil T1 en categoría /Engineering, Electrical & Electronic/)

- *O. Perpiñán*, solaR: Solar Radiation and Photovoltaic Systems with R, Journal of Statistical Software, 2012. 50(9), (1-32). \\ (Índice de impacto: 4.91, Tercil T1 en categoría /Statistics & Probability/)

- *O. Perpiñán*, Cost of energy and mutual shadows in a two-axis tracking PV system, Renewable Energy, 2011, [[http://dx.doi.org/10.1016/j.renene.2011.12.001][10.1016/j.renene.2011.12.001]]. \\ (Índice de impacto: 2.98, Tercil T1 en categoría /Energy & Fuels/)

- *O. Perpiñán* y E. Lorenzo, Analysis and synthesis of the variability of irradiance and PV power time series with the wavelet transform, Solar Energy, 85:1 (188-197), 2010, [[http://dx.doi.org/10.1016/j.solener.2010.08.013][10.1016/j.solener.2010.08.013]]).\\ (Índice de impacto: 2.48, Tercil T1 en categoría /Energy & Fuels/)

- *O. Perpiñán*, Statistical analysis of the performance and simulation of a two-axis tracking PV system, Solar Energy, 83:11(2074–2085), 2009, [[http://dx.doi.org/10.1016/j.solener.2009.08.008][10.1016/j.solener.2009.08.008]]. \\(Índice de impacto: 2.01, Tercil T2 en categoría /Energy & Fuels/)

- *O. Perpiñán*, E. Lorenzo, M. A. Castro, y R. Eyras. Energy payback time of grid connected PV systems: comparison between tracking and fixed systems. Progress in Photovoltaics: Research and Applications, 17:137-147, 2009.\\ (Índice de impacto: 4.7; Tercil T1 en categoría /Energy & Fuels/)

- *O. Perpiñán*, E. Lorenzo, M. A. Castro, y R. Eyras. On the complexity of radiation models for PV energy production calculation. Solar Energy, 82:2 (125-131), 2008\\ (Índice de impacto: 1.61, Tercil T2 en categoría /Energy & Fuels/)

- *O. Perpiñán*, E. Lorenzo, y M. A. Castro. On the calculation of energy produced by a PV grid-connected system. Progress in Photovoltaics: Research and Applications, 15(3):265–274, 2007.\\ (Índice de impacto: 2.18; Tercil T1 en categoría /Energy & Fuels/)

** Publicaciones Nacionales

- Fernando Garnacho Vecino, Miguel Ángel Sánchez-Urán González, Javier
        Ortego La Moneda, F. Alvarez, *O. Perpiñán*,
        Revisión periódica del estado del aislamiento de los cables de
        AT mediante medidas de DPs on line, Energía: Ingeniería
        energética y medioambiental, ISSN 0210-2056, Año nº 37, Nº
        230, 2011, págs. 38-46.

- *O. Perpiñán*, E. Lorenzo, M.A. Castro, Estimación de sombras mutuas
  entre seguidores y optimización de separaciones, Era Solar, ISSN
  0212-4157, Nº. 131, 2006 , págs. 28-37

- *O. Perpiñán*, M.A. Castro, E. Lorenzo, Análisis y
  comparación de funcionamiento de grandes plantas: photocampa y forum
  Energía: Ingeniería energética y medioambiental, ISSN 0210-2056, Año
  nº 32, Nº 190, 2006, págs. 63-68

- J. Carretero, L. Mora-López, *O. Perpiñán*, A. Pereña, Mariano Sidrach
  de Cardona Ortín, I. Martínez, M. Aritio, Parque tecnológico de
  Andalucía: tecnología OPC. Monitorización wireless de una
  instalación fotovoltaica de 56 kWp, Era solar: Energías renovables,
  ISSN 0212-4157, Nº. 127, 2005, págs. 56-65.

- Arancha Perpiñán Lamigueiro, *O. Perpiñán*, Elena Carmen
  Horno, Bombeo de agua para riego con energía solar fotovoltáica:
  sistemas de bombeo solar directo Riegos y drenajes XXI, ISSN
  0213-3660, Nº 144, 2005, págs. 68-74

- *O. Perpiñán*, R. Eyras, D. Jiménez, Antonio Gómez
        Avilés-Casco, Sistemas fotovoltaicos en el Parque de las
        Ciencias de Granada Era solar: Energías renovables, ISSN
        0212-4157, Nº. 104, 2001, págs. 16-21



* Proyectos de Investigación Subvencionados
(Ordenados por fecha de inicio descendente)

** PVCROPS. PhotoVoltaic Cost reduction, Reliability, Operational performance, Prediction and Simulation
- Entidad Financiadora: Comisión Europea
- Cantidad Financiada (€): 5800352
- Referencia del Proyecto: 308468
- Tipo de convocatoria: UE
- Entidades Participantes: UPM, UPNA, UEVORA, Cl Senes, Acciona, Ingeteam, ONE, Sources of the Bulgarian Academy of Sciences, DIT, Sunswitch SA, Rtnoe, Apere
- Duración: desde 01/11/2012 hasta 31/10/2015 N° total de meses: 36
- Investigador Principal: Luis Narvarte
- Nº Investigadores: 10
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Predicción de productividad de sistemas fotovoltaicos a partir de modelos numéricos de predicción meteorológica y medidas terrestres.
  - Caracterización de las fluctuaciones en sistemas fotovoltaicos de gran tamaño en el contexto de su integración en las redes eléctricas convencionales.
  - Predicción de categorías de fluctuaciones en sistemas fotovoltaicos a partir de modelos numéricos de predicción meteorológica y medidas terrestres.
  - Desarrollo de dos paquetes software publicados con licencia GNU/GPL
  - Publicación de resultados en artículo JCR.

** ENERGOS: optimización de la cargabilidad de las líneas

- Entidad Financiadora: CDTI
- Cantidad Financiada (€): 380306
- Referencia del Proyecto: CEN-2009-1048
- Tipo de convocatoria: Nacional
- Entidades Participantes: EUITI, Unión Fenosa
- Duración: desde 07/07/2009 hasta 31/12/2012 N° total de meses: 42
- Investigador Principal: Fernando Garnacho
- Nº Investigadores: 8
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Revisión del estado del arte de sensores de alta frecuencia para Descargas Parciales en cables de MT.
  - Definición de parámetros característicos de Descargas Parciales en el contexto de su medida y clasificación en entornos industriales ruidosos.
  - Desarrollo de métodos de caracterización y clasificación no supervisada de colecciones de Descargas Parciales
  - Desarrollo de software pdCluster publicado con licencia GNU/GPL.
  - Publicación de resultados en artículo JCR.

** Caracterización de la variabilidad y comportamiento ante las perturbaciones de las plantas fotovoltaicas

- Entidad Financiadora: Red Eléctrica de España
- Tipo de convocatoria: Contrato con Empresa Privada
- Entidades Participantes: UPM, UPNA, Acciona
- Duración: desde 01/01/2009 hasta 31/12/2011 N° total de meses: 36
- Investigador Principal: Eduardo Lorenzo
- Nº Investigadores: 8
- Responsabilidad: Investigador colaborador
- Aportación del investigador:
  - Caracterización de las fluctuaciones de radiación y potencia en sistemas fotovoltaicos mediante la transformada wavelet.
  - Análisis de las fluctuaciones de potencia en una planta fotovoltaica de gran tamaño según el tipo de día y la distancia entre generadores
  - Publicación de resultados en dos artículos JCR.

** Umbráculo Móvil

- Entidad Financiadora: Ministerio de Educación y Ciencia
- Cantidad Financiada (€): 1469000
- Referencia del Proyecto: PCT-120000-2007-34
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, Jeronimo Vega Arquitectura, IES-UPM, Trim
- Duración: desde 01/07/2007 hasta 31/12/2008 N° total de meses: 18
- Investigador Principal: Oscar Perpiñán
- Nº Investigadores: 15
- Responsabilidad: Investigador principal
- Aportación del Investigador: 
  - Coordinación del proyecto
  - Desarrollo un seguidor horizontal adaptable a las particulares condiciones de una cubierta de un edificio.
  - Análisis de las condiciones de instalación y explotación de sistemas de seguimiento en zonas elevadas, frente a la experiencia de instalación en terreno común.
  - Diseño de sistema de conversión de potencia con inversores de gran tamaño.

** Desarrollo de una Plataforma para la Monitorizacion y Seguimiento de Sistemas Fotovoltaicos

- Entidad Financiadora: Corporacion Tecnologica de Andalucia
- Cantidad Financiada (€): 400034
- Referencia del Proyecto: 06109D1A
- Tipo de convocatoria: CC.AA.
- Entidades Participantes: Isofotón, ISM, Universidad de Malaga
- Duración: desde 01/01/2007 hasta 31/12/2007 N° total de meses: 12
- Investigador Principal: Oscar Perpiñán
- Nº Investigadores: 15
- Responsabilidad: Investigador principal
- Aportación del Investigador:
  - Definición de requisitos del sistema.
  - Selección de equipos a monitorizar.
  - Diseño de sistemas de prueba.
  - Revisión de implementación de herramientas software.
  - Implementación de prototipos.
  - Estudio del estado del arte de comunicaciones en sistemas de monitorización.

** Desarrollo y Caracterizacion de Tejados y Fachadas Fotovoltaicas Ventiladas Integradas en Edificios

- Entidad Financiadora: Ministerio de Educación y Ciencia
- Cantidad Financiada (€): 452289
- Referencia del Proyecto: CIT-120000-2007-89
- Tipo de convocatoria: Nacional
- Entidades Participantes: CIMNE, Isofotón, Pich-Aguilera Arquitectos, Universidad de Lleida
- Duración: desde 01/07/2007 hasta 30/06/2008 N° total de meses: 12
- Investigador Principal: Jordi Cipriano
- Nº Investigadores: 15
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Estudio del estado del arte de generadores fotovoltaicos en fachadas ventiladas.
  - Consultoría en la implementación de herramientas software de simulación con TRNSYS.
  - Definición del generador fotovoltaico y equipos asociados. 
  - Diseño de prototipos para prueba en campo.
  - Análisis de datos de funcionamiento.

** Optimización del Diseño Electrico de Modulos Fotovoltaicos para Minimizar las Perdidas de Potencia por Dispersion y Evitar los Puntos Calientes

- Entidad Financiadora: Ministerio de Industria, Turismo y Comercio
- Cantidad Financiada (€): 338691
- Referencia del Proyecto: FIT-030000-2007-264
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, CIEMAT
- Duración: desde 01/01/2007 hasta 31/12/2008 N° total de meses: 24
- Investigador Principal: Paula Sanchez-Friera
- Nº Investigadores: 6
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - En el diseño y ejecución de sistemas fotovoltaicos de gran tamaño obra especial relevancia el impacto de sombras mutuas y las perdidas por dispersión, objeto de este proyecto de investigacion. Dado que los cinco investigadores restantes son expertos en diseño y fabricacion de dispositivos fotovoltaicos, la aportacion del solicitante consistió en aportar el conocimiento de ingenieria desde la experiencia en campo.

** Conector de Paneles Dinamico CPD-1 y Convertidor Multipuente Multipotencia CMM-1

- Entidad Financiadora: Ministerio de Industria, Turismo y Comercio
- Cantidad Financiada (€): 354347
- Referencia del Proyecto: FIT-120000-2007-100
- Tipo de convocatoria: Nacional
- Entidades Participantes: LACECAL, Isofotón, Calor Económico del Bierzo
- Duración: desde 01/07/2007 hasta 30/06/2008 N° total de meses: 12
- Investigador Principal: Jose Antonio Dominguez Vazquez (LACECAL)
- Nº Investigadores: 12
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de prototipos para pruebas.
  - Diseño de sistema de monitorización.
  - Estudio del estado del arte de equipos inversores.

** MODEN II

- Entidad Financiadora: Ministerio de Industria, Turismo y Comercio
- Cantidad Financiada (€): 391753
- Referencia del Proyecto: FIT-120000-2006-138
- Tipo de convocatoria: Nacional
- Entidades Participantes: LACECAL, Isofotón, INGETEAM, Calor Económico del Bierzo
- Duración: desde 01/01/2006 hasta 31/12/2007 N° total de meses: 24
- Investigador Principal: Pablo Gutierrez Martin (LACECAL)
- Nº Investigadores: 13
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño y ejecucion de sistemas fotovoltaicos de conexion a red
  - Diseño de sistemas fotovoltaicos para probar los equipos diseñados
  - Coordinación de la participacion de Isofoton en este proyecto
** Mejora de la Calidad del Servicio Energetico en las Aplicaciones de Electrificacion Rural 
- Entidad Financiadora: Ministerio de Educación y Ciencia
- Cantidad Financiada (€): 356943
- Referencia del Proyecto: CIT-120000-2005-75
- Tipo de convocatoria: Nacional
- Entidades participantes: Isofotón, IES-UPM, Universidad Internacional de Andalucia, Universidad de Santiago de Compostela
- Duración: desde 01/01/2005 hasta 31/12/2005 N° total de meses: 12
- Investigador Principal: Oscar Perpiñán
- Nº Investigadores: 8
- Responsabilidad: Investigador principal
- Aportación del Investigador:
  - Coordinación del proyecto.
  - Diseño de prototipo de sistema de bombeo de agua de gran tamaño acoplado a sistemas fotovoltaicos de seguimiento.
  - Desarrollo y validación de software de simulación de sistemas de bombeo fotovoltaico.
  - Supervisión del diseño de sistemas de riego con sistemas de bombeo.

** Caracterización del Comportamiento Térmico de la Fachada PVSKIN y su Interaccion con Edificios Modelo en Clima Mediterráneo

- Entidad Financiadora: Ministerio de Educacion y Ciencia
- Cantidad Financiada (€): 152520
- Referencia del Proyecto: CIT-120000-2005-74
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, CIMNE
- Duración: desde 01/01/2005 hasta 15/05/2006 N° total de meses: 18
- Investigador Principal: Ramón Eyras Daguerre
- Nº Investigadores: 7
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de prototipos para medida.
  - Diseño de sistemas de monitorización para pruebas.
  - Coordinación de tareas de ingeniería.

** Sistema de Desalinizacion mediante Osmosis Inversa Alimentado con Energía Solar Fotovoltaica

- Entidad Financiadora: CDTI
- Cantidad Financiada (€): 626600
- Referencia del Proyecto: 04-0624
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, Instituto Tecnológico de Canarias, VEOLIA
- Duración: desde 01/07/2004 hasta 31/12/2005 N° total de meses: 18
- Investigador Principal: Ramon Eyras Daguerre
- Nº Investigadores: 10
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de sistema fotovoltaico autónomo sin acumulación de energía que permite el funcionamiento autónomo de la planta en zonas aisladas sin suministro eléctrico.
  - Supervisión de la optimización de los circuitos hidráulicos, eléctricos y el sistema de control para el correcto y viable funcionamiento de la planta y el parque fotovoltaico.

** Grandes Centrales Fotovoltaicas

- Entidad Financiadora: Ministerio de Educación y Ciencia
- Cantidad Financiada (€): 107690
- Referencia del Proyecto: FIT-120000-2004-24
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, IES-UPM, Universidad Internacional de Andalucía
- Duración: desde 01/01/2004 hasta 31/12/2004 N° total de meses: 12
- Investigador Principal: Oscar Perpiñán
- Nº Investigadores: 8
- Responsabilidad: Investigador principal
- Aportación del Investigador:
  - Coordinación de proyecto.
  - Análisis de datos de funcionamiento de plantas fotovoltaicas de gran tamaño.
  - Métodos de diseño en plantas fotovoltaicas de gran tamaño con tecnologías de seguimiento.
  - Análisis de métodos de cálculo de productividad en sistemas fotovoltaico con diferentes fuentes de radiación.
  - Desarrollo de herramienta software solaR.
  - Publicación de resultados en 4 artículos JCR.
  - Defensa de Tesis Doctoral

** Grandes Centrales Fotovoltaicas

- Entidad Financiadora: Ministerio de Educación
- Cantidad Financiada (€): 313052
- Referencia del Proyecto: CIT-120000-2005-68
- Tipo de convocatoria: Nacional
- Entidades Participantes: Isofotón, IES-UPM, Universidad Internacional de Andalucía
- Duración: desde 01/01/2005 hasta 31/12/2005 N° total de meses: 12
- Investigador Principal: Oscar Perpiñán
- Nº Investigadores: 8
- Responsabilidad: Investigador principal
- Aportación del Investigador:
  - Coordinación de proyecto.
  - Análisis de datos de funcionamiento de plantas fotovoltaicas de gran tamaño.
  - Métodos de diseño en plantas fotovoltaicas de gran tamaño con tecnologías de seguimiento.
  - Análisis de métodos de cálculo de productividad en sistemas fotovoltaico con diferentes fuentes de radiación.
  - Desarrollo de herramienta software solaR.
  - Publicación de resultados en 4 artículos JCR.
  - Defensa de Tesis Doctoral

** Combinación de Energías Renovables con Almacenamiento Intermedio de H2 y Pila de Combustible (TINA)
- Entidad Financiadora: Junta de Andalucía
- Cantidad Financiada (€): 532358
- Referencia del Proyecto: 2002000874
- Tipo de convocatoria: CC.AA.
- Entidades Participantes: Isofotón, BESEL, David Fuel
- Duración: desde 02/01/2004 hasta 30/06/2005 N° total de meses: 18
- Investigador Principal: Jesús Alonso
- Nº Investigadores: 6
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño del sistema fotovoltaico.
  - Supervisión de la instalación del prototipo.
  - Diseño del sistema de monitorización.
  - Análisis de resultados de funcionamiento.

** Heliodomo: Nuevo Concepto de Vivienda Autosuficiente

- Entidad Financiadora: Ministerio de Educacion y Ciencia
- Cantidad Financiada (€): 205165
- Referencia del Proyecto: BIA2004-05234
- Tipo de convocatoria: Nacional
- Entidades Participantes: IES-UPM, CEDINT, Isofoton
- Duración: desde 13/12/2004 hasta 12/12/2007 N° total de meses: 36
- Investigador Principal: F. Javier Neila González
- Nº Investigadores: 15
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de sistemas fotovoltaicos en condiciones de integración arquitectónica
  - Análisis del funcionamiento de sistemas fotovoltaicos en condiciones de integración arquitectónica
  - Selección de materiales apropiados por su sinergia con generadores fotovoltaicos

** Sevilla PV

- Entidad Financiadora: Comisión Europea
- Cantidad Financiada (€): 2759244
- Referencia del Proyecto: NNE5-2001-00767
- Tipo de convocatoria: UE
- Entidades Participantes: Solucar, Solartec, CIEMAT, BP Solar, Saint-Gobain, Atersa, IDAE, Isofoton, WIP
- Duración: desde 01/02/2004 hasta 31/07/2007 N° total de meses: 54
- Investigador Principal: Rafael Osuna
- Nº Investigadores: 50
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de sistemas fotovoltaicos con modulos fotovoltaicos con sistema externo de concentracion 2x.
** PV Generators Integrated into Sound Barriers

- Entidad Financiadora: Comisión Europea
- Cantidad Financiada (€): 4950039
- Referencia del Proyecto: NNE5/2000/397
- Tipo de convocatoria: UE
- Entidades Participantes: Isofoton, Ayto. Helmond, Ayto. Leganes, Fraunhofer Ise, Biohaus
- Duración: desde 01/01/2001 hasta 31/12/2003 N° total de meses: 24
- Investigador Principal: Ramón Eyras Daguerre
- Nº Investigadores: 25
- Participación: Investigador colaborador
- Aportación del Investigador:
  - Supervisión del desarrollo de un módulo fotovoltaico sobre cubierta cerámica para atenuar ruido.
  - Supervisión de pruebas de funcionamiento del módulo desarrollado en probeta acústica.
  - Diseño de sistema fotovoltaico de gran tamaño en talud de autovía.

** PV Grid Connected in a Car Parking

- Entidad Financiadora: Comisión Europea
- Cantidad Financiada (€): 2612600
- Referencia del Proyecto: NNE5/1999/772
- Tipo de convocatoria: UE
- Entidades Participantes:, ISOFOTON, BERGE Y CIA, Universidad de Northumbria, Biohaus, ICAEN, Sunwatt
- Duración: desde 01/01/2000 hasta 31/12/2002 N° total de meses: 24
- Investigador Principal: Ramon Eyras Daguerre
- Nº Investigadores: 20
- Responsabilidad: Investigador colaborador
- Aportación del Investigador:
  - Diseño de un sistema fotovoltaico de gran tamaño integrado en una estructura de aparcamiento.
  - Estudio del arte de sistemas de conversión de potencia.
  - Diseño de sistemas de conversión de potencia variados para comparativa.
  - Diseño de sistema de monitorización para investigación.
  - Análisis de datos de funcionamiento. Modelado y validación de modelos.
  - Publicación de resultados en artículos JCR
  - Estudio del estado del arte de sistemas de seguridad eléctrica en sistemas fotovoltaicos con público.


* Comunicaciones y Ponencias Presentadas a Congresos
** EnerSol World Sustainable Energy Forum 2014
Congreso Internacional organizado por SETCOR. Túnez, Noviembre 2014.

- Linke turbidity prediction for improving solar radiation forecasting, F. Antonanzas-Torres, F. J. Martinez-de-Pison, *O. Perpiñán*, R. Nunes, Carlos Coimbra

** VI Jornadas de Usuarios de R
Congreso Nacional organizado por la Comunidad R-Hispano. Santiago de Compostela, Octubre 2014. 

- meteoForecast: predicciones meteorológicas de modelos NWP en R, *O. Perpiñán*, M. P. Almeida

** 17th International Congress on  Project Management and Engineering 
Congreso Internacional organizado por AEIPRO. Málaga, Julio 2013

- Downscaling of Solar Irradiation from Satellite Models, F. Antoñanzas,J. Antoñanzas, F.J. Martínez de Pisón, M. J. Alía Martínez, *Perpiñán, O.*
** CIGRE SESSION 2012
Congreso Internacional organizado por CIGRE. Francia, Agosto 2012

- New Procedure To Determine Insulation Condition Of High Voltage Equipment By Means Of PD Measurements In Service, F. Garnacho, M.A. Sánchez-Urán, J. Ortego, F. Álvarez, *O. Perpiñán*, E. Puelles, R. Moreno, D. Prieto, D. Ramos

** III Jornadas de usuarios de R
Congreso Nacional organizado por la Comunidad R-Hispano. Madrid, Noviembre 2011

- Comparativa y análisis de variabilidad espacial entre medidas de radiación solar terrestre y satelital, F. Antoñanzas, F. Cañizares, R. Morales, M. Ojeda, *O. Perpiñán*

- solaR: geometría, radiación y energía solar en R, *O. Perpiñán*

- Datos geográficos de tipo raster en R, J. van Etten, *O. Perpiñán*, R. J. Hijmans

** JICABLE 2011
Congreso Internacional organizado por Jicable. Francia, Junio 2011

- PD monitoring system of HV cable, F. Garnacho, M.A. Sánchez-Urán, J. Ortego, J. Moreno, F. Álvarez, *O. Perpiñán*

** 22nd European Photovoltaic Solar Energy Conference
Congreso Internacional organizado por WIP. Milán, Septiembre 2007

- PV Solar Tracking Systems Analysis, R. Sorichetti, *O. Perpiñán*

** 21st European Photovoltaic Solar Energy Conference
Congreso Internacional organizado por WIP. Dresden, Septiembre 2006

- A Real Case Of Building Integrated PV, Isofotón Offices In Málaga, F. Arribas, I. Eyras, J. Vega, L. Mendez, J.J. Garcia, *O. Perpiñán*, R. Eyras

** 9th International Congress on  Project Management and Engineering
Congreso Internacional organizado por AEIPRO. Málaga, Junio de 2005

- Instalación De Energía Solar En La Nueva Fabrica De Isofotón En El P.T.A De Málaga, L. Mendez, J. Vega, J.J. Garcia, I. Eyras, F. Arribas, *O. Perpiñán*, R. Eyras

** 20th European Photovoltaic Solar Energy Conference
Congreso Internacional organizado por WIP. Barcelona, Junio 2005

- Analysis And Comparison Of Performance Of Large Plantes: Photocampa And Forum, *O. Perpiñán*, E. Lorenzo, M.A. Castro, R. Eyras

** XII Congreso Ibérico e VII Congresso Ibero-Americano de Energía Solar
Congreso Nacional organizado por AEDES-ISES. Vigo, Septiembre 2004

- Monitorización Wireless De Instalación Fotovoltaica De 56 kWp En El Parque Tecnológico De Andalucia Basada En La Tecnologia OPC , M. Sidrach, J. Carretero, A. Pereña, L. Mora, M. Aritio, *O. Perpiñán*

- Centrales Hibridas Solar-Diesel: Nuestra Experiencia, M. Mazzorana, L. Carrasco, E. Horno, R. Eyras, *O. Perpiñán*, L.  Narvarte

- Sistema Solar Térmico Y Fotovoltaico En Hotel Urbano, J. Garcia, *O. Perpiñán*, F. Ramirez, R. Eyras, J. Vega

- Experiencia En Sistemas De Bombeo Solar Y Simulación Matemática De Bombeos Solares Con Equipos Estándar , E. Horno, *O. Perpiñán*, J. Hungria, I. Rai, R. Eyras

- Fachada Doble Fotovoltaica PVskin: Prototipos, Investigación Y Desarrollo, I. Eyras, F. Arribas, M.A. Bofill, J. Vega, *O. Perpiñán*

- Solarízate: Proyecto Escuelas Solares De Greenpeace-Idae, A. Gonzalez, *O. Perpiñán*, F. Ramirez, R. Eyras

** 19th European Photovoltaic Solar Energy Conference
Congreso Internacional organizado por WIP. Paris, Junio 2004

- PV Soundless: World Record Along The Highway -- A PV Sound Barrier With 500 kWp And Ceramic Based PV Modules, M. Grottke, T. Suker, R.Eyras, J.Gorbeña, *O. Perpiñán*, A. Voigt, A.  Thiel, M.Spendel, K.Gherlicher, G. Frisen, R.Gambi, K.Kellner

- Architecture And PV - Discussion And Experiences, J. Vega, *O. Perpiñán*

- Forum Solar: A Large PV Pergola For Forum 2004, *O. Perpiñán*, A. Gonzalez, I. Eyras, R. Eyras

- PV Pumping Systems For Domestic Water Supply-Cases Of Study, R. Eyras, *O. Perpiñán*, J. Hungria, I. Rai

** 7th Congreso Internacional de Ingenieria de Proyectos
Congreso Internacional organizado por AEIPRO. Pamplona, Octubre 2003

- Instalación De Energía Solar Térmica Con Maquina De Absorción, J. Giacardi, I. Eyras, J.J. Garcia, *O. Perpiñán*, R. Eyras

- Ósmosis Inversa Alimentada Mediante Energía Solar Fotovoltaica, *O. Perpiñán*, M. Aritio, J. Hungria, T. Espino, L. Guerrero, J.M. Ortega

** 3rd World Conference on Photovoltaic Energy Conversion
Congreso Internacional organizado por IEEE. Osaka, Octubre 2003

- Photocampa: Design And Performance Of The PV System, *O. Perpiñán*, N. Pearsall, L. Mendez, R. Eyras

- Architectural Integration Of Grid Connected Photovoltaic Systems For Schools In Coslada, D. Jimenez, L. M. Carrasco, R. Eyras, *O. Perpiñán*, A. Gonzalez

** 5th European Conference on Noise Control
Congreso Internacional organizado por CNR-Instituto di Acustica. Napoles, Mayo 2003

- Photovoltaic Modules Integrated In Novel Noise Barrier Elements, T. Erge, R. Eyras, *O. Perpiñán*, A. Gonzalez, E. Rossler

** 6th Congreso Internacional de Ingeniería de Proyectos
Congreso Internacional organizado por AEIPRO. Barcelona, Octubre 2002

- Photocampa: Sistema Fotovoltaico Integrado En Estructura De Aparcamiento, *O. Perpiñán*, S. Izquierdo, L. Mendez, S. Salat, R. Eyras

** PV in Europe
Congreso Internacional organizado por WIP. Roma, Octubre 2002

- PVSOUNDLESS: Large PV Sound Barrier Along A Railway, A. Gonzalez, R. Eyras, *O. Perpiñán*, T. Erge

- FIVE Project. Integration Of PV Systems On Health Emergency Vehicles. Results And Conclusions, G. Almonacid, F.J. Muñoz, J. De La Casa, J. C. Hernandez, J. De La Casa Cardenas, J.D. Aguilar, P. Serrano, A. Mantero, A. Jimenez, E.  Ferrando, *O. Perpiñán*, R. Eyras, 

** EuroSun 2002
Congreso Internacional organizado por ISES. Bologna, Junio 2002

- PVSOUNDLESS: large PV sound barrier along a railway, A.G. Marsiñach, O.Perpiñán, T.Erge, R.Eyras

** 17th European Photovoltaic Solar Energy Conference
Congreso Internacional organizado por WIP. Munich, Octubre 2001

- Photocampa: PV System Integrated Into A Large Car Park, *O. Perpiñán*, N. Pearsall, L. Mendez, W. Ernst, M. Schneider, R. Eyras

- Special Module Types For PV Systems In High-Profile Buildings, *O. Perpiñán*, J. Vega, R. Eyras

- PV Pergola For The Chapel Of Men, Guayasamin Foundation, Ecuador, R. Eyras, Y. Fernandez, *O. Perpiñán*

- Integration Of PV Systems On Health Emergency Vehicles, G. Almonacid, F. J. Muñoz, J. De La Casa, J.C. Hernandez, J. De La Casa Cardenas, P. Serrano, A. Mantero, A. Jimenez, E. Ferrando, O.  Perpiñán, R. Eyras

- Quality Control of Luminaries in SHS, L. Narvarte, E. Lorenzo, *O. Perpiñán*, M.A. Egido


* Desarrollos

** solaR

Paquete software basado en =R= compuesto por un conjunto de funciones destinadas al cálculo de la radiación solar incidente en sistemas fotovoltaicos y a la simulación del funcionamiento de diferentes aplicaciones de esta tecnología energética. En la versión actual de este paquete se incluyen funciones que permiten realizar todas las etapas de cálculo desde la radiación global en el plano horizontal hasta la productividad final de sistemas fotovoltaicos de conexión a red y de bombeo. Esta herramienta se publica con una licencia libre GNU/GPL en el [[http://cran.r-project.org/web/packages/solaR/index.html][Comprehensive R Archive Network (CRAN)]] y en la web http://oscarperpinan.github.io/solar/.

** rasterVis
Paquete software basado en =R= para la visualización e interacción gráfica de datos espaciales masivos. Esta herramienta se publica con una licencia libre GNU/GPL en el [[http://cran.r-project.org/web/packages/rasterVis/index.html][Comprehensive R Archive Network (CRAN)]] y en su página web http://oscarperpinan.github.io/rastervis.

** meteoForecast
Paquete software basado en =R= que permite obtener predicciones de modelos numéricos meteorológicos producidos por diferentes servicios en formato raster o como series temporales. Esta herramienta se publica con una licencia libre GNU/GPL en el [[http://cran.r-project.org/web/packages/meteoForecast/index.html][Comprehensive R Archive Network (CRAN)]] y en su página web [[https://github.com/oscarperpinan/meteoForecast/]].

Este desarrollo software es uno de los resultados del proyecto europeo PVCROPS. Ha sido empleado en el artículo M. Pinho Almeida, O. Perpiñán, L. Narvarte, "PV Power Forecast Using a Nonparametric PV Model Solar Energy" Solar Energy, 2015. 

** PVF
Paquete software basado en =R= que permite realizar predicciones de potencia producida por un sistema FV. Esta herramienta se publica con una licencia libre GNU/GPL en la página web http://github.com/iesiee/PVF.

Este desarrollo software es uno de los resultados del proyecto europeo PVCROPS. Ha sido empleado en el artículo M. Pinho Almeida, O. Perpiñán, L. Narvarte, "PV Power Forecast Using a Nonparametric PV Model Solar Energy" Solar Energy, 2015. 

** pdCluster
Paquete software basado en =R= para la cuantificación, clasificación y análisis de importancia de variables de señales de descargas parciales en equipos de Alta Tensión. Esta herramienta se publica con una licencia libre GNU/GPL. Está accesible desde la página web http://oscarperpinan.github.io/pdcluster/.

Este desarrollo software es uno de los resultados del proyecto CENIT ENERGOS. Ha sido empleado en el artículo O. Perpiñán,
M.A. Sánchez-Urán, F. Álvarez, J. Ortego, F. Garnacho, Signal analysis and feature generation for pattern identification of
partial discharges in high-voltage equipment, Electric Power Systems Research, 2013, 95:C (56-65).

** pxR
Paquete software basado en =R= para la manipulación de fuentes de datos basadas en el formato PC-Axis, habitualmente empleado por instituciones nacionales e internacionales para la publicación de información.  Esta herramienta se publica con una licencia libre GNU/GPL. Está accesible desde el Comprehensive R Archive Network (CRAN) en la página web http://cran.r-project.org/web/packages/pxR/.

* Cursos y Seminarios Impartidos

- Curso "Introducción a R" (8 horas) para profesores de la UPM (Instituto de Ciencias de la Educación, UPM, Diciembre 2014)

- Curso "Introducción a R" (10 horas) para investigadores del CEIGRAM-UPM (Noviembre 2014)

- Taller "Visualización de Series Temporales" en las VI Jornadas de Usuarios de R (Santiago de Compostela, Octubre 2014)

- Taller "Visualización de Datos Raster" en las VI Jornadas de Usuarios de R (Santiago de Compostela, Octubre 2014)

- Curso "Introducción a R" (8 horas) para profesores de la UNED (UNED, Marzo 2013).

- Curso "R avanzado" (8 horas) para profesores de la UNED (UNED, Marzo 2013).

- Ponencia "Data Visualization with R" dentro del Máster "Data Driven Methods in Environmental Management and Conservation" del (Instituto de Empresa, Febrero 2013).

- Participación en las ediciones 2014/2015, 2013/2014, 2012/2013, 2011/2012, 2010/2011 y 2010/2009 del Master propio de Energías Renovables y Medio Ambiente de la UPM, organizado por la ETSIDI-UPM, impartiendo el tema ``Diseño de plantas FV con seguimiento solar'' con una duración de 4,5 horas.

- Curso ``Instalaciones de energía solar'', impartido del 15/09/10 al 16/10/11 con una duración de 109 horas, organizado por la ETSI-Montes-UPM, impartiendo el modulo ``Sistemas fotovoltaicos conectados a red'', con una duración de 5 horas.

- Formación a distancia sobre Diseño y Optimización de Sistemas Fotovoltaicos al responsable de Sistemas Solares de la empresa MENA. Este proceso de formación, con una duración de 6 meses, se ha basado en las potencialidades del paquete software solaR, reseñado anteriormente.

- Curso ``Técnico en energías renovables'', impartido del 01/09/09 al 27/10/09 con una duración de 200 horas, organizado por la ETSIDI-UPM, impartiendo el modulo ``Sistemas fotovoltaicos conectados a red'', con una duración de 5 horas.

- Curso ``Instalaciones de energía solar'', impartido del 15/09/09 al 16/10/09 con una duración de 109 horas, organizado por la ETSI-Montes-UPM, impartiendo el modulo ``Sistemas fotovoltaicos conectados a red'', con una duración de 5 horas.

- Curso ``Técnico en instalaciones solares en edificios'', impartido del 01/09/09 al 15/10/09, organizado por la ETSIDI-UPM, impartiendo el módulo ``Sistemas fotovoltaicos conectados a red'', con una duración de 25 horas.

- Participacion en el curso ``Técnico en instalaciones fotovoltaicas y eolicas'', impartido del 06/10/09 al 04/12/09, organizado por la ETSIDI-UPM, impartiendo el módulo ``Sistemas fotovoltaicos conectados a red'', con una duración de 15 horas.

- Participacion en el curso ``Energías renovables'', ediciones 2011/2012, 2010/2011 y 2009/2010, con una duración de 200 horas, organizado por la ETSI-Montes-UPM, impartiendo el módulo ``Energía solar fotovoltaica'', con una duración de 5 horas.

* Cursos y Seminarios recibidos

/(Ordenados por duración)/

- Experto Universitario en Métodos Avanzados de Estadística Aplicada (UNED, 2009/2010, 625 horas)

- Aplicación de las energías renovables (ETSII-UPC, 2001/2002, 300 horas)

- Caracterización de la radiación solar como recurso energético (CIEMAT, 2006, 30 horas)

- Estadística en la investigación experimental (ICE-UPM, 2010, 28 horas)

- Estadística comparativa y de investigación para uno y dos grupos de muestras (ICE-UPM, 2009, 24 horas)

- Introduction to mathematical optimization techniques applied to power systems generation operation planning (Universidad Pontificia de Comillas, 2003, 20 horas)

- Curso eléctrico de Media Tensión (Pedro Giner Editorial, 2003, 18 horas)

- Rechargeable batteries (OTTI Kolleg, 2002, 20 horas)

- Wavelets en Estadística (ICE-UPM, 2010, 8 horas)


* Becas, Ayudas y Premios recibidos

- Premio Extraordinario de Doctorado.
- Beca de Colaboración dentro del Grupo de Bioingeniería y Telemedicina de la ETSIT en el contexto del proyecto europeo "Worldwide Emergency Telemedicine Services" (WETS) (1998)


* Actividad en Empresas y Profesión Libre

- Octubre 2010- Enero 2009: Ejercicio libre de la profesión:
  Consultoría sobre diseño y análisis de funcionamiento de sistemas fotovoltaicos.

- Diciembre 2008- Enero 2007: Subdirector Técnico de ISOFOTON
  - Equipo compuesto por 10 personas. 
  - Responsable de las Áreas de:
    - I+D+i :: desarrollo de nuevas aplicaciones, coordinación y participación en proyectos colaborativos de I+D+i
    - Producto BOS :: desarrollo de equipos electrónicos para diferentes aplicaciones, supervision de los equipos disponibles en el mercado
    - Difusión Técnica :: elaboración de documentación, formación de técnicos e ingenieros, participación en conferencias y cursos de especialización
 
- Enero 2007-Mayo 2002: Gerente de Ingeniería (Dpto. Técnico de ISOFOTON)
  - Responsable de ofertas técnicas, diseño de proyectos y proyectos de ejecución.
  - Equipo compuesto por 7 personas.

- Mayo 2002-Noviembre 2001: Gerente de Instalaciones (Dpto. Técnico de ISOFOTON)
  - Responsable de gestión y dirección de proyectos, y jefatura de obras.
  - Equipo compuesto por 7 personas.

- Noviembre 2001-Marzo 2000: Ingeniero de Proyectos (Dpto. Técnico de ISOFOTON)



* Otros Méritos Docentes o de Investigación

** Acreditaciones

  - Acreditación de la Agencia Nacional de Evaluación de la Calidad y Acreditación (ANECA) para la figura de Profesor Titular de Universidad.

  - Evaluación positiva por la Agencia Nacional de Evaluación de la Calidad y Acreditación (ANECA) para la figura de Profesor Contratado Doctor.

  # - Evaluación positiva por la Agencia de Calidad, Acreditación y Prospectiva de las Universidades de Madrid (ACAP) para la figura de Profesor Contratado Doctor y Profesor Ayudante Doctor.

  - Evaluación favorable de la actividad docente según el programa DOCENTIA de la ANECA durante el período comprendido entre noviembre de 2008 y junio de 2011.

** Miembro de tribunal de Tesis Doctoral

  - ``El Proyecto Pierre Auger como Red de Sistemas Fotovoltaicos Aislados de Alta Estadística'' (Iago Rodriguez Cabo, USC 2015)

  - ``Predicción espacio-temporal de la irradiancia solar global a corto plazo en España mediante geoestadística y redes neuronales artificiales'' (Federico Vladimir Gutierrez Corea, UPM 2014)

  - ``Energía solar fotovoltaica: competitividad y evaluación económica, comparativa y modelos'' (Eduardo Collado Fernández, UNED 2009)

** Revisor para revistas

  - /Solar Energy/

  - /Applied Energy/

  - /Journal of Solar Engineering/

  - /Computers and Geosciences/

  - /IET Renewable Power Generation/

  - /Journal of Statistical Software/

** Asociaciones

  - Presidente del Comité Organizador y miembro del Comité Científico de las III Jornadas de Usuarios de R (http://r-es.org/III+Jornadas).

  - Miembro del Comité Científico de las IV, V, y VI Jornadas de Usuarios de R (http://r-es.org/IV+Jornadas, http://r-es.org/V+Jornadas, http://r-es.org/VI+Jornadas).

  - Vocal de la Asociación de Usuarios de R.

  - Miembro de la Comisión Técnica de la Asociación de la Industria Fotovoltaica (ASIF) hasta Diciembre del 2008.

  - Miembro del grupo GT C del Comité de Normalización SC82 hasta Diciembre del 2008.


# * Diligencia de Curriculum

# El abajo firmante D. Oscar Perpiñán Lamigueiro,
# ## Nº. de Registro de Personal 5073216257-Y200200064, Profesor
# ## Asociado,
# se responsabiliza de la veracidad de los datos en el presente
# curriculum, comprometiéndose a aportar, en su caso, las pruebas
# documentales que le sean requeridas.
# ## \vspace{10mm
# \begin{flushright
#   Madrid, a 28 de Julio de 2010.
#   \par\end{flushright
# \vspace{10mm
# \begin{flushright
#   Firmado: Oscar Perpiñán Lamigueiro
#   \par\end{flushright
  
  

* Otros Méritos
- Vocal de la Comisión de Extensión Universitaria de la ETSIDI-UPM
